### ISSUE TITLE
Kubernetes native?

### ISSUE THREAD

**Issue by captjt** [fabric8-services/keycloak-deployment#53]
Is this docker image compatible with native Kubernetes? I am trying to port our Keycloak deployment over to Postgres and make sure it's HA. There is not much documentation that is clear enough on these sort of things with Keycloak. I appreciate the help!

**Comment by alexeykazakov** [comment]
This image should be compatible with native Kubernetes but we haven't tried/tested it with Kubernetes. You can also take a look at this image https://github.com/fabric8io/keycloak

**Comment by captjt** [comment]
Perfect thank you so much @alexeykazakov! I'll close this comment if that's alright then.
